### PR TITLE
use Test::Requires to test for minimum version, rather than a bare eval.

### PR DESCRIPTION
**Pull request by karenetheridge**
self-explanatory.  This is exactly what Test::Requires is for, and every time someone tests $@ explicitly, somewhere a kitten dies.

### CODE REVIEW

**Comment by xenoterracide** [comment]
I notice your patch modifies Makefile.PL but as this is a dzil plugin that is generated. could you amend your patch to not modify the makefile?

**Comment by xenoterracide** [comment]
I cleaned up the patch, fixed the whitespace and the deleted part of {{$NEXT}} in changes, and fixed in 0.001004 please be careful to review the diffstat when contributing patches

**Comment by xenoterracide** [comment]
already fixed

**Comment by karenetheridge** [comment]
Sorry, I'm not quite sure what you're asking here.  If Makefile.PL is not the master source of the requirements for this distribution, it shouldn't be committed in git (something like dist.ini should be instead).  And what do you mean about diffstat?

**Comment by xenoterracide** [comment]
The primary branch is the build branch, not the source branch (allows for easy final source reading) I fixed it already. I really have no idea how people don't notice that there are multiple upstream branches when they clone. I'm going to have  to work out a way of saying "don't modify this file, it's generated". diffstat is `git diff --stat` technically, though in my case I mean moreso `git diff --stat --patch`.  You would have noticed that you mangled the `{{$NEXT}}` in the Changes file

**Comment by karenetheridge** [comment]
Or you could just not commit any files that are auto-generated :)

**Comment by xenoterracide** [comment]
http://www.xenoterracide.com/2011/07/experience-with-having-non-distzilla.html I'd rather fix your patch

**Pull request closed without merging**
